# -*- coding: utf-8 -*-
"""メイン.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cnpKiEAwELGdq1GAflhqriQWMivJhp9
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import copy
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from torchvision.transforms.functional import to_pil_image

from sklearn.model_selection import train_test_split, StratifiedKFold

# =========================================================
# 0. 設定
# =========================================================
BASE_DIR = Path('/content/drive/MyDrive/dataset')  # 必要ならここだけ変更
RESULT_DIR = Path('/content/drive/MyDrive/defect_cv_with_final_test')
RESULT_DIR.mkdir(parents=True, exist_ok=True)

IMAGE_SIZE = 512
BATCH_SIZE = 8
NUM_WORKERS = 0   # Colab安定性重視
NUM_EPOCHS = 20
NUM_FOLDS = 5
RANDOM_STATE = 42

FINAL_TEST_SIZE = 0.10
ROTATION_DEGREES = 30
LEARNING_RATE = 1e-4

BETA = 2.0
TARGET_RECALL = 0.90
THRESHOLDS = np.linspace(0.05, 0.95, 19)

FINAL_MODEL_NAME = 'final_resnet18_512_with_holdout_test.pth'
FINAL_TRAIN_HISTORY_NAME = 'final_train_history.csv'
FINAL_TEST_RESULT_NAME = 'final_test_result.json'
AGGREGATE_RESULT_NAME = 'aggregate_summary.json'

# =========================================================
# 1. 画像一覧取得
# =========================================================
def get_image_files(folder: Path):
    exts = ['*.jpg', '*.jpeg', '*.png', '*.bmp', '*.webp']
    files = []
    for ext in exts:
        files.extend(folder.glob(ext))
        files.extend(folder.glob(ext.upper()))
    return sorted(files)

good_dir = BASE_DIR / 'good'
bad_dir = BASE_DIR / 'bad'

good_files = get_image_files(good_dir)
bad_files = get_image_files(bad_dir)

all_paths = np.array([str(p) for p in bad_files + good_files])
all_labels = np.array([0] * len(bad_files) + [1] * len(good_files))  # bad=0, good=1

print("Total bad :", len(bad_files))
print("Total good:", len(good_files))
print("Total all :", len(all_paths))

# =========================================================
# 2. 最初に final test を分離
# =========================================================
trainval_paths, test_paths, trainval_labels, test_labels = train_test_split(
    all_paths,
    all_labels,
    test_size=FINAL_TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=all_labels
)

print("\n===== Hold-out split =====")
print("trainval size:", len(trainval_paths))
print("final test size:", len(test_paths))
print("trainval bad/good:", int(np.sum(trainval_labels == 0)), int(np.sum(trainval_labels == 1)))
print("final test bad/good:", int(np.sum(test_labels == 0)), int(np.sum(test_labels == 1)))

pd.DataFrame({
    'path': trainval_paths,
    'label': trainval_labels
}).to_csv(RESULT_DIR / 'trainval_split.csv', index=False)

pd.DataFrame({
    'path': test_paths,
    'label': test_labels
}).to_csv(RESULT_DIR / 'final_test_split.csv', index=False)

# =========================================================
# 3. Dataset
# =========================================================
class DefectDataset(Dataset):
    def __init__(self, paths, labels, transform=None):
        self.paths = list(paths)
        self.labels = list(labels)
        self.transform = transform

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        img_path = self.paths[idx]
        label = self.labels[idx]

        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)

        return image, label, img_path

# =========================================================
# 4. Transform
# =========================================================
train_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=ROTATION_DEGREES),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

valid_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# =========================================================
# 5. モデル作成
# =========================================================
def create_model(device):
    weights = models.ResNet18_Weights.DEFAULT
    model = models.resnet18(weights=weights)
    in_features = model.fc.in_features
    model.fc = nn.Linear(in_features, 2)
    return model.to(device)

# =========================================================
# 6. 指標計算
# =========================================================
def calculate_metrics_from_confusion(tp, tn, fp, fn):
    total = tp + tn + fp + fn
    acc = (tp + tn) / total if total > 0 else 0.0
    bad_recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    bad_precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    return acc, bad_recall, bad_precision

def fbeta_score(precision, recall, beta=2.0):
    beta2 = beta ** 2
    denom = beta2 * precision + recall
    if denom == 0:
        return 0.0
    return (1 + beta2) * precision * recall / denom

def predict_with_threshold(bad_probs, threshold):
    return np.where(bad_probs >= threshold, 0, 1)

def confusion_from_preds(labels, preds):
    tp = int(np.sum((labels == 0) & (preds == 0)))
    tn = int(np.sum((labels == 1) & (preds == 1)))
    fp = int(np.sum((labels == 1) & (preds == 0)))
    fn = int(np.sum((labels == 0) & (preds == 1)))
    return tp, tn, fp, fn

def metrics_from_probs(labels, bad_probs, threshold, beta=2.0):
    preds = predict_with_threshold(bad_probs, threshold)
    tp, tn, fp, fn = confusion_from_preds(labels, preds)
    acc, bad_recall, bad_precision = calculate_metrics_from_confusion(tp, tn, fp, fn)
    bad_fbeta = fbeta_score(bad_precision, bad_recall, beta=beta)

    return {
        'threshold': float(threshold),
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn,
        'acc': float(acc),
        'bad_recall': float(bad_recall),
        'bad_precision': float(bad_precision),
        'bad_fbeta': float(bad_fbeta),
        'preds': preds
    }

def find_best_threshold(labels, bad_probs, thresholds, beta=2.0, target_recall=None):
    results = []
    for t in thresholds:
        m = metrics_from_probs(labels, bad_probs, t, beta=beta)
        results.append(m)

    if target_recall is not None:
        candidates = [r for r in results if r['bad_recall'] >= target_recall]
        if len(candidates) > 0:
            best = max(
                candidates,
                key=lambda x: (x['bad_fbeta'], x['bad_recall'], x['bad_precision'], x['acc'])
            )
            best['selection_mode'] = f"target_recall>={target_recall}"
            return best, results

    best = max(
        results,
        key=lambda x: (x['bad_fbeta'], x['bad_recall'], x['bad_precision'], x['acc'])
    )
    best['selection_mode'] = "max_fbeta"
    return best, results

# =========================================================
# 7. 学習 / 推論
# =========================================================
def train_one_epoch(model, dataloader, criterion, optimizer, device, beta=2.0):
    model.train()

    running_loss = 0.0
    total = 0
    tp = tn = fp = fn = 0

    for images, labels, _paths in dataloader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        preds = torch.argmax(outputs, dim=1)

        running_loss += loss.item() * images.size(0)
        total += labels.size(0)

        tp += ((labels == 0) & (preds == 0)).sum().item()
        tn += ((labels == 1) & (preds == 1)).sum().item()
        fp += ((labels == 1) & (preds == 0)).sum().item()
        fn += ((labels == 0) & (preds == 1)).sum().item()

    epoch_loss = running_loss / total
    epoch_acc, epoch_bad_recall, epoch_bad_precision = calculate_metrics_from_confusion(tp, tn, fp, fn)
    epoch_bad_fbeta = fbeta_score(epoch_bad_precision, epoch_bad_recall, beta=beta)

    return {
        'loss': epoch_loss,
        'acc': epoch_acc,
        'bad_recall': epoch_bad_recall,
        'bad_precision': epoch_bad_precision,
        'bad_fbeta': epoch_bad_fbeta,
        'tp': tp, 'tn': tn, 'fp': fp, 'fn': fn
    }

def collect_probs(model, dataloader, criterion, device):
    model.eval()

    running_loss = 0.0
    total = 0

    all_labels = []
    all_bad_probs = []
    all_paths = []
    all_images_cpu = []

    with torch.no_grad():
        for images, labels, paths in dataloader:
            images_gpu = images.to(device, non_blocking=True)
            labels_gpu = labels.to(device, non_blocking=True)

            outputs = model(images_gpu)
            loss = criterion(outputs, labels_gpu)

            probs = F.softmax(outputs, dim=1)
            bad_probs = probs[:, 0].detach().cpu().numpy()

            running_loss += loss.item() * images_gpu.size(0)
            total += labels_gpu.size(0)

            all_labels.extend(labels.numpy())
            all_bad_probs.extend(bad_probs.tolist())
            all_paths.extend(paths)
            all_images_cpu.extend([img.cpu() for img in images])

    return {
        'loss': running_loss / total,
        'labels': np.array(all_labels),
        'bad_probs': np.array(all_bad_probs),
        'paths': all_paths,
        'images_cpu': all_images_cpu
    }

# =========================================================
# 8. 失敗画像保存
# =========================================================
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32).reshape(3, 1, 1)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32).reshape(3, 1, 1)

def denormalize_tensor(img_tensor):
    img = img_tensor.numpy()
    img = img * IMAGENET_STD + IMAGENET_MEAN
    img = np.clip(img, 0, 1)
    return torch.tensor(img)

def save_failure_images(images_cpu, labels, bad_probs, preds, paths, save_dir: Path):
    fn_dir = save_dir / 'FN_bad_to_good'
    fp_dir = save_dir / 'FP_good_to_bad'
    fn_dir.mkdir(parents=True, exist_ok=True)
    fp_dir.mkdir(parents=True, exist_ok=True)

    records = []

    for i, (img_tensor, label, prob, pred, path_str) in enumerate(zip(images_cpu, labels, bad_probs, preds, paths)):
        label = int(label)
        pred = int(pred)
        path_str = str(path_str)
        base_name = Path(path_str).stem

        denorm = denormalize_tensor(img_tensor)
        pil_img = to_pil_image(denorm)

        if label == 0 and pred == 1:
            save_path = fn_dir / f'{i:04d}_{base_name}_badprob_{prob:.4f}.png'
            pil_img.save(save_path)
            records.append({
                'type': 'FN',
                'original_path': path_str,
                'saved_path': str(save_path),
                'label': label,
                'pred': pred,
                'bad_prob': float(prob)
            })

        elif label == 1 and pred == 0:
            save_path = fp_dir / f'{i:04d}_{base_name}_badprob_{prob:.4f}.png'
            pil_img.save(save_path)
            records.append({
                'type': 'FP',
                'original_path': path_str,
                'saved_path': str(save_path),
                'label': label,
                'pred': pred,
                'bad_prob': float(prob)
            })

    if len(records) > 0:
        pd.DataFrame(records).to_csv(save_dir / 'failure_records.csv', index=False)

# =========================================================
# 9. device / loss / utility
# =========================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

class_weights = torch.tensor([1.0, 1.0], dtype=torch.float32).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)

cv_dir = RESULT_DIR / 'cv'
cv_dir.mkdir(parents=True, exist_ok=True)

def save_json(path: Path, obj: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)

def load_json(path: Path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

skf = StratifiedKFold(n_splits=NUM_FOLDS, shuffle=True, random_state=RANDOM_STATE)
fold_splits = list(skf.split(trainval_paths, trainval_labels))

print(f"Prepared {len(fold_splits)} folds.")

# =========================================================
# 10. 1 fold 実行関数
# =========================================================
def run_fold(fold_number: int):
    assert 1 <= fold_number <= NUM_FOLDS, f"fold_number must be 1..{NUM_FOLDS}"

    train_idx, valid_idx = fold_splits[fold_number - 1]

    fold_dir = cv_dir / f'fold_{fold_number}'
    fold_dir.mkdir(parents=True, exist_ok=True)

    summary_path = fold_dir / 'summary.json'
    history_path = fold_dir / 'history.csv'
    valid_pred_path = fold_dir / 'valid_predictions.csv'
    model_path = fold_dir / f'best_model_fold_{fold_number}.pth'

    fold_train_paths = trainval_paths[train_idx]
    fold_train_labels = trainval_labels[train_idx]
    fold_valid_paths = trainval_paths[valid_idx]
    fold_valid_labels = trainval_labels[valid_idx]

    print("\n" + "=" * 100)
    print(f"Fold {fold_number}/{NUM_FOLDS}")
    print("=" * 100)
    print("train size:", len(fold_train_paths))
    print("valid size:", len(fold_valid_paths))
    print("train bad/good:", int(np.sum(fold_train_labels == 0)), int(np.sum(fold_train_labels == 1)))
    print("valid bad/good:", int(np.sum(fold_valid_labels == 0)), int(np.sum(fold_valid_labels == 1)))

    if summary_path.exists() and history_path.exists() and valid_pred_path.exists() and model_path.exists():
        print(f"[Fold {fold_number}] already completed. Skip.")
        return

    train_dataset = DefectDataset(fold_train_paths, fold_train_labels, transform=train_transform)
    valid_dataset = DefectDataset(fold_valid_paths, fold_valid_labels, transform=valid_transform)

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )

    valid_loader = DataLoader(
        valid_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )

    model = create_model(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

    best_score = -1.0
    best_epoch = -1
    best_threshold = 0.5
    best_model_wts = copy.deepcopy(model.state_dict())
    best_epoch_summary = None

    history = []

    for epoch in range(NUM_EPOCHS):
        train_metrics = train_one_epoch(model, train_loader, criterion, optimizer, device, beta=BETA)
        valid_out = collect_probs(model, valid_loader, criterion, device)

        best_thr_info, thr_table = find_best_threshold(
            labels=valid_out['labels'],
            bad_probs=valid_out['bad_probs'],
            thresholds=THRESHOLDS,
            beta=BETA,
            target_recall=TARGET_RECALL
        )

        valid_metrics = best_thr_info
        score = valid_metrics['bad_fbeta']

        is_better = False
        if score > best_score:
            is_better = True
        elif np.isclose(score, best_score):
            if best_epoch_summary is None or valid_metrics['bad_recall'] > best_epoch_summary['bad_recall']:
                is_better = True

        if is_better:
            best_score = score
            best_epoch = epoch + 1
            best_threshold = valid_metrics['threshold']
            best_model_wts = copy.deepcopy(model.state_dict())
            best_epoch_summary = {
                'epoch': best_epoch,
                'threshold': float(best_threshold),
                'acc': float(valid_metrics['acc']),
                'bad_recall': float(valid_metrics['bad_recall']),
                'bad_precision': float(valid_metrics['bad_precision']),
                'bad_fbeta': float(valid_metrics['bad_fbeta']),
                'tp': int(valid_metrics['tp']),
                'tn': int(valid_metrics['tn']),
                'fp': int(valid_metrics['fp']),
                'fn': int(valid_metrics['fn']),
                'selection_mode': valid_metrics['selection_mode']
            }

        epoch_record = {
            'fold': fold_number,
            'epoch': epoch + 1,
            'train_loss': train_metrics['loss'],
            'train_acc': train_metrics['acc'],
            'train_bad_recall': train_metrics['bad_recall'],
            'train_bad_precision': train_metrics['bad_precision'],
            'train_bad_fbeta': train_metrics['bad_fbeta'],
            'valid_loss': float(valid_out['loss']),
            'valid_acc': float(valid_metrics['acc']),
            'valid_bad_recall': float(valid_metrics['bad_recall']),
            'valid_bad_precision': float(valid_metrics['bad_precision']),
            'valid_bad_fbeta': float(valid_metrics['bad_fbeta']),
            'valid_threshold': float(valid_metrics['threshold']),
            'tp': int(valid_metrics['tp']),
            'tn': int(valid_metrics['tn']),
            'fp': int(valid_metrics['fp']),
            'fn': int(valid_metrics['fn']),
            'selection_mode': valid_metrics['selection_mode']
        }
        history.append(epoch_record)

        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}]")
        print(f"  Train Loss: {train_metrics['loss']:.4f} | Train Acc: {train_metrics['acc']:.4f} | Train Bad Recall: {train_metrics['bad_recall']:.4f} | Train Bad Precision: {train_metrics['bad_precision']:.4f} | Train F{BETA:.0f}: {train_metrics['bad_fbeta']:.4f}")
        print(f"  Valid Loss: {valid_out['loss']:.4f} | Valid Acc: {valid_metrics['acc']:.4f} | Valid Bad Recall: {valid_metrics['bad_recall']:.4f} | Valid Bad Precision: {valid_metrics['bad_precision']:.4f} | Valid F{BETA:.0f}: {valid_metrics['bad_fbeta']:.4f}")
        print(f"  Valid Threshold: {valid_metrics['threshold']:.2f} | Selection: {valid_metrics['selection_mode']}")
        print(f"  TP={valid_metrics['tp']} TN={valid_metrics['tn']} FP={valid_metrics['fp']} FN={valid_metrics['fn']}")
        print("-" * 100)

    model.load_state_dict(best_model_wts)

    final_valid_out = collect_probs(model, valid_loader, criterion, device)
    final_metrics = metrics_from_probs(
        labels=final_valid_out['labels'],
        bad_probs=final_valid_out['bad_probs'],
        threshold=best_threshold,
        beta=BETA
    )

    save_failure_images(
        images_cpu=final_valid_out['images_cpu'],
        labels=final_valid_out['labels'],
        bad_probs=final_valid_out['bad_probs'],
        preds=final_metrics['preds'],
        paths=final_valid_out['paths'],
        save_dir=fold_dir / 'failure_images'
    )

    valid_pred_df = pd.DataFrame({
        'path': final_valid_out['paths'],
        'label': final_valid_out['labels'],
        'bad_prob': final_valid_out['bad_probs'],
        'pred': final_metrics['preds']
    })
    valid_pred_df.to_csv(valid_pred_path, index=False)

    torch.save(model.state_dict(), model_path)
    pd.DataFrame(history).to_csv(history_path, index=False)

    summary = {
        'fold': fold_number,
        'best_epoch': int(best_epoch),
        'best_threshold': float(best_threshold),
        'acc': float(final_metrics['acc']),
        'bad_recall': float(final_metrics['bad_recall']),
        'bad_precision': float(final_metrics['bad_precision']),
        'bad_fbeta': float(final_metrics['bad_fbeta']),
        'tp': int(final_metrics['tp']),
        'tn': int(final_metrics['tn']),
        'fp': int(final_metrics['fp']),
        'fn': int(final_metrics['fn']),
        'model_path': str(model_path)
    }
    save_json(summary_path, summary)

    print(f"[Fold {fold_number}] Best Epoch: {best_epoch}")
    print(f"[Fold {fold_number}] Best Threshold: {best_threshold:.2f}")
    print(f"[Fold {fold_number}] Acc={final_metrics['acc']:.4f} Recall={final_metrics['bad_recall']:.4f} Precision={final_metrics['bad_precision']:.4f} F{BETA:.0f}={final_metrics['bad_fbeta']:.4f}")
    print(f"[Fold {fold_number}] saved to: {fold_dir}")

run_fold(1)

run_fold(2)

run_fold(3)

run_fold(4)

run_fold(5)

# =========================================================
# 11. CV集計 + OOF threshold + FINAL_EPOCHS決定
# =========================================================
fold_results = []
epoch_history_all_folds = []
oof_probs = np.zeros(len(trainval_paths), dtype=np.float32)
oof_labels = trainval_labels.copy()

for fold_number in range(1, NUM_FOLDS + 1):
    train_idx, valid_idx = fold_splits[fold_number - 1]
    fold_dir = cv_dir / f'fold_{fold_number}'

    summary_path = fold_dir / 'summary.json'
    history_path = fold_dir / 'history.csv'
    valid_pred_path = fold_dir / 'valid_predictions.csv'

    if not (summary_path.exists() and history_path.exists() and valid_pred_path.exists()):
        raise FileNotFoundError(f"Fold {fold_number} is not completed yet: {fold_dir}")

    summary = load_json(summary_path)
    history_df = pd.read_csv(history_path)
    valid_pred_df = pd.read_csv(valid_pred_path)

    fold_results.append(summary)
    epoch_history_all_folds.extend(history_df.to_dict('records'))

    loaded_probs = valid_pred_df['bad_prob'].values.astype(np.float32)
    if len(loaded_probs) != len(valid_idx):
        raise ValueError(f"Fold {fold_number}: valid_predictions length mismatch")

    oof_probs[valid_idx] = loaded_probs

cv_summary_df = pd.DataFrame(fold_results)
cv_summary_df.to_csv(RESULT_DIR / 'cv_summary.csv', index=False)

print("\n" + "=" * 100)
print("CV Summary")
print("=" * 100)
print(cv_summary_df)

for col in ['acc', 'bad_recall', 'bad_precision', 'bad_fbeta', 'best_threshold', 'best_epoch']:
    print(f"{col}: mean={cv_summary_df[col].mean():.4f}, std={cv_summary_df[col].std(ddof=0):.4f}")

epoch_history_df = pd.DataFrame(epoch_history_all_folds)
epoch_history_df.to_csv(RESULT_DIR / 'all_epoch_history.csv', index=False)

epoch_mean_df = epoch_history_df.groupby('epoch').agg({
    'train_loss': 'mean',
    'train_acc': 'mean',
    'train_bad_recall': 'mean',
    'train_bad_precision': 'mean',
    'train_bad_fbeta': 'mean',
    'valid_loss': 'mean',
    'valid_acc': 'mean',
    'valid_bad_recall': 'mean',
    'valid_bad_precision': 'mean',
    'valid_bad_fbeta': ['mean', 'std']
}).reset_index()

epoch_mean_df.columns = [
    'epoch',
    'train_loss_mean',
    'train_acc_mean',
    'train_bad_recall_mean',
    'train_bad_precision_mean',
    'train_bad_fbeta_mean',
    'valid_loss_mean',
    'valid_acc_mean',
    'valid_bad_recall_mean',
    'valid_bad_precision_mean',
    'valid_bad_fbeta_mean',
    'valid_bad_fbeta_std'
]

epoch_mean_df.to_csv(RESULT_DIR / 'epoch_mean_summary.csv', index=False)

best_epoch_row = epoch_mean_df.sort_values(
    by=['valid_bad_fbeta_mean', 'valid_bad_recall_mean', 'valid_bad_precision_mean'],
    ascending=[False, False, False]
).iloc[0]

FINAL_EPOCHS = int(best_epoch_row['epoch'])

print("\n" + "=" * 100)
print("Final epoch selected from 5-fold mean")
print("=" * 100)
print(best_epoch_row)
print("Selected FINAL_EPOCHS =", FINAL_EPOCHS)

global_best_thr_info, global_thr_table = find_best_threshold(
    labels=oof_labels,
    bad_probs=oof_probs,
    thresholds=THRESHOLDS,
    beta=BETA,
    target_recall=TARGET_RECALL
)

global_thr_df = pd.DataFrame(global_thr_table)
global_thr_df.to_csv(RESULT_DIR / 'global_threshold_search.csv', index=False)

FINAL_THRESHOLD = float(global_best_thr_info['threshold'])

print("\n" + "=" * 100)
print("Global OOF Threshold Search Result")
print("=" * 100)
print(f"Selected Threshold: {FINAL_THRESHOLD:.2f}")
print(f"Selection Mode    : {global_best_thr_info['selection_mode']}")
print(f"Acc               : {global_best_thr_info['acc']:.4f}")
print(f"Bad Recall        : {global_best_thr_info['bad_recall']:.4f}")
print(f"Bad Precision     : {global_best_thr_info['bad_precision']:.4f}")
print(f"Bad F{BETA:.0f}           : {global_best_thr_info['bad_fbeta']:.4f}")
print(f"TP={global_best_thr_info['tp']} TN={global_best_thr_info['tn']} FP={global_best_thr_info['fp']} FN={global_best_thr_info['fn']}")

aggregate_summary = {
    'final_epochs': int(FINAL_EPOCHS),
    'final_threshold': float(FINAL_THRESHOLD),
    'selection_mode': global_best_thr_info['selection_mode'],
    'oof_acc': float(global_best_thr_info['acc']),
    'oof_bad_recall': float(global_best_thr_info['bad_recall']),
    'oof_bad_precision': float(global_best_thr_info['bad_precision']),
    'oof_bad_fbeta': float(global_best_thr_info['bad_fbeta']),
    'beta': float(BETA),
    'target_recall': float(TARGET_RECALL)
}
save_json(RESULT_DIR / AGGREGATE_RESULT_NAME, aggregate_summary)

print("\nSaved aggregate summary to:", RESULT_DIR / AGGREGATE_RESULT_NAME)

# =========================================================
# 12. train_val 全体で最終学習
# =========================================================
aggregate_summary_path = RESULT_DIR / AGGREGATE_RESULT_NAME
if not aggregate_summary_path.exists():
    raise FileNotFoundError("Run セル16 first.")

aggregate_summary = load_json(aggregate_summary_path)
FINAL_EPOCHS = int(aggregate_summary['final_epochs'])
FINAL_THRESHOLD = float(aggregate_summary['final_threshold'])

print("FINAL_EPOCHS   =", FINAL_EPOCHS)
print("FINAL_THRESHOLD=", FINAL_THRESHOLD)

trainval_dataset = DefectDataset(trainval_paths, trainval_labels, transform=train_transform)
trainval_loader = DataLoader(
    trainval_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

final_model = create_model(device)
final_optimizer = torch.optim.Adam(final_model.parameters(), lr=LEARNING_RATE)

final_train_history = []

for epoch in range(FINAL_EPOCHS):
    train_metrics = train_one_epoch(final_model, trainval_loader, criterion, final_optimizer, device, beta=BETA)
    final_train_history.append({
        'epoch': epoch + 1,
        'train_loss': train_metrics['loss'],
        'train_acc': train_metrics['acc'],
        'train_bad_recall': train_metrics['bad_recall'],
        'train_bad_precision': train_metrics['bad_precision'],
        'train_bad_fbeta': train_metrics['bad_fbeta']
    })

    print(f"Final Epoch [{epoch+1}/{FINAL_EPOCHS}]")
    print(f"  Train Loss: {train_metrics['loss']:.4f} | Train Acc: {train_metrics['acc']:.4f} | Train Bad Recall: {train_metrics['bad_recall']:.4f} | Train Bad Precision: {train_metrics['bad_precision']:.4f} | Train F{BETA:.0f}: {train_metrics['bad_fbeta']:.4f}")
    print("-" * 100)

final_model_path = RESULT_DIR / FINAL_MODEL_NAME
torch.save(final_model.state_dict(), final_model_path)
pd.DataFrame(final_train_history).to_csv(RESULT_DIR / FINAL_TRAIN_HISTORY_NAME, index=False)

print("Saved final model to:", final_model_path)

# =========================================================
# 13. hold-out final test で1回だけ評価
# =========================================================
aggregate_summary_path = RESULT_DIR / AGGREGATE_RESULT_NAME
final_model_path = RESULT_DIR / FINAL_MODEL_NAME

if not aggregate_summary_path.exists():
    raise FileNotFoundError("Run セル16 first.")
if not final_model_path.exists():
    raise FileNotFoundError("Run セル17 first.")

aggregate_summary = load_json(aggregate_summary_path)
FINAL_EPOCHS = int(aggregate_summary['final_epochs'])
FINAL_THRESHOLD = float(aggregate_summary['final_threshold'])

print("FINAL_EPOCHS   =", FINAL_EPOCHS)
print("FINAL_THRESHOLD=", FINAL_THRESHOLD)

test_dataset = DefectDataset(test_paths, test_labels, transform=valid_transform)
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

final_model = create_model(device)
final_model.load_state_dict(torch.load(final_model_path, map_location=device))
final_model.eval()

test_out = collect_probs(final_model, test_loader, criterion, device)
test_metrics = metrics_from_probs(
    labels=test_out['labels'],
    bad_probs=test_out['bad_probs'],
    threshold=FINAL_THRESHOLD,
    beta=BETA
)

print(f"Final Test Threshold: {FINAL_THRESHOLD:.2f}")
print(f"Final Test Acc      : {test_metrics['acc']:.4f}")
print(f"Final Test Recall   : {test_metrics['bad_recall']:.4f}")
print(f"Final Test Precision: {test_metrics['bad_precision']:.4f}")
print(f"Final Test F{BETA:.0f}       : {test_metrics['bad_fbeta']:.4f}")
print(f"TP={test_metrics['tp']} TN={test_metrics['tn']} FP={test_metrics['fp']} FN={test_metrics['fn']}")

save_failure_images(
    images_cpu=test_out['images_cpu'],
    labels=test_out['labels'],
    bad_probs=test_out['bad_probs'],
    preds=test_metrics['preds'],
    paths=test_out['paths'],
    save_dir=RESULT_DIR / 'final_test_failure_images'
)

with open(RESULT_DIR / FINAL_TEST_RESULT_NAME, 'w', encoding='utf-8') as f:
    json.dump({
        'final_epochs': FINAL_EPOCHS,
        'final_threshold': FINAL_THRESHOLD,
        'acc': float(test_metrics['acc']),
        'bad_recall': float(test_metrics['bad_recall']),
        'bad_precision': float(test_metrics['bad_precision']),
        'bad_fbeta': float(test_metrics['bad_fbeta']),
        'tp': int(test_metrics['tp']),
        'tn': int(test_metrics['tn']),
        'fp': int(test_metrics['fp']),
        'fn': int(test_metrics['fn']),
        'beta': BETA,
        'target_recall': TARGET_RECALL,
        'model_path': str(final_model_path)
    }, f, ensure_ascii=False, indent=2)

print("\nSaved final test result to:", RESULT_DIR / FINAL_TEST_RESULT_NAME)
print("Saved results to         :", RESULT_DIR)
print("Done.")